# Generated by Django 3.1.3 on 2020-11-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
