// CONFIGURACION DE LOS ACTIONS TYPES


// Autenticacion
export const GET_INFO = "GET_INFO";
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
// Productos
export const CARGANDO_PRODUCTOS = "CARGANDO_PRODUCTOS";
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_MIS_PRODUCTOS = 'OBTENER_MIS_PRODUCTOS';
export const OBTENER_MIS_PRODUCTOS_ERROR = 'OBTENER_MIS_PRODUCTOS';
export const NUEVO_PRODUCTO = 'NUEVO_PRODUCTO';
export const NUEVO_PRODUCTO_ERROR = 'NUEVO_PRODUCTO_ERROR';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
// Carrito
export const AGREGAR_CARRITO = "AGREGAR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
export const COMPRA_REALIZADA = "COMPRA_REALIZADA";
export const COMPRA_ERROR = "COMPRA_ERROR";
// Reportes
export const VENTAS_POR_PRODUCTO = "VENTAS_POR_PRODUCTO";
export const VENTAS_TOTAL = "VENTAS_TOTAL";
export const PROMEDIO_PRODUCTOS = "PROMEDIO_PRODUCTOS";